use Profile.Label newtype for typechecked union instead of AnyRef (#6371)
* use Profile.Label newtype for typechecked union instead of AnyRef

- includes port of some of interpreter

- demonstrating its efficacy is the compiler error in this commit:

daml-lf/interpreter/src/main/scala/com/digitalasset/daml/lf/speedy/Compiler.scala:267: error: type mismatch;
 found   : com.daml.lf.speedy.SExpr.SEBuiltinRecursiveDefinition
 required: com.daml.lf.speedy.Profile.Label
    (which expands to)  com.daml.lf.speedy.Profile.LabelModule.Module.T
            withLabel(ref, ref)
                      ^

  What was likely intended was to write `ref.ref` here; that is the assumption
  the `Event#label` rendering function makes, anyway.  Now, we type-check that
  the labelling matches the renderer.

* let Profile make arbitrary Labels

* fix null and missing `.ref` calls for labelling

* one more null => LabelUnset

* no changelog

CHANGELOG_BEGIN
CHANGELOG_END

* implicitNotFound message never used

* ritual offering of the dot and parens

Co-authored-by: Martin Huschenbett <martin.huschenbett@posteo.me>

Co-authored-by: Martin Huschenbett <martin.huschenbett@posteo.me>