Update the CC toolchain for MacOS M1 compatibility
Use nixpkgs `nix-support/cc-cflags` file to provide default flags
instead of using `makeWrapper`. On M1 there was an issue where passing
`-l` flags or `-isystem` to `cc -v` would cause the following errors:

```
lang version 11.1.0
Target: aarch64-apple-darwin
Thread model: posix
InstalledDir: /nix/store/v6iidz79b425hli98g45xq9iblapn1zy-clang-11.1.0/bin
"/nix/store/b82mvqzvdx5mh1n9n77v8h5vk9fgqrxj-clang-wrapper-11.1.0/bin/ld" -demangle -lto_library /nix/store/v6iidz79b425hli98g45xq9iblapn1zy-clang-11.1.0/lib/libLTO.dylib -dynamic -arch arm64 -platform_version macos 11.0.0 0.0.0 -o a.out -L/nix/store/hc8a94w57ppwmn2gscm56pvlwi3zhyh1-libSystem-11.0.0/lib -L/nix/store/6f5ygwif1r523jj2qfwfiwix0fga4rgp-clang-11.1.0-lib/lib -L/nix/store/7pkxnbhpi0c10w18rirj8zxz3wv571nj-libcxx-11.1.0/lib -no_uuid -arch arm64 -lSystem /nix/store/b82mvqzvdx5mh1n9n77v8h5vk9fgqrxj-clang-wrapper-11.1.0/resource-root/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture arm64:
"_main", referenced from:
 implicit entry/start for main executable
ld: symbol(s) not found for architecture arm64
```

This also includes additional standard library search paths:
`-isystem ${llvmPackages_12.libcxx.dev}/include/c++/v1` alone is not
enough because some headers in it are [wrapper
headers](https://gcc.gnu.org/onlinedocs/cpp/Wrapper-Headers.html) that
use `include_next` directives. For these to resolve we need to add the
compiler's builtin headers to the search path as well.

This also sets `-Wno-elaborated-enum-base` to avoid build failures of
absl on MacOS Monterey M1.
```
In file included from external/com_google_absl/absl/time/internal/cctz/src/time_zone_lookup.cc:26:                                                                                                                                                                              In file included from /nix/store/jjkm7x4zfifqgsxlbhkamzg0vc9wzip4-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFTimeZone.h:13:
/nix/store/jjkm7x4zfifqgsxlbhkamzg0vc9wzip4-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:474:9: error: non-defining declaration of enumeration with a fixed underlying type is only permitted as a standalone declaration;
 missing list of enumerators? [-Welaborated-enum-base]
typedef CF_ENUM(CFIndex, CFComparisonResult) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/jjkm7x4zfifqgsxlbhkamzg0vc9wzip4-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:169:55: note: expanded from macro 'CF_ENUM'
\#define CF_ENUM(...) __CF_ENUM_GET_MACRO(__VA_ARGS__, __CF_NAMED_ENUM, __CF_ANON_ENUM, )(__VA_ARGS__)
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/jjkm7x4zfifqgsxlbhkamzg0vc9wzip4-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:134:48: note: expanded from macro '__CF_ENUM_GET_MACRO'
\#define __CF_ENUM_GET_MACRO(_1, _2, NAME, ...) NAME
                                               ^
/nix/store/jjkm7x4zfifqgsxlbhkamzg0vc9wzip4-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:142:75: note: expanded from macro '__CF_NAMED_ENUM'
\#define __CF_NAMED_ENUM(_type, _name)     enum __CF_ENUM_ATTRIBUTES _name : _type _name; enum _name : _type
                                                                          ^~~~~~~
                                                                          In file included from external/com_google_absl/absl/time/internal/cctz/src/time_zone_lookup.cc:26:                                                                                                                                                                              In file included from /nix/store/jjkm7x4zfifqgsxlbhkamzg0vc9wzip4-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFTimeZone.h:18:
In file included from /nix/store/jjkm7x4zfifqgsxlbhkamzg0vc9wzip4-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFString.h:17:
/nix/store/jjkm7x4zfifqgsxlbhkamzg0vc9wzip4-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFCharacterSet.h:62:9: error: non-defining declaration of enumeration with a fixed underlying type is only permitted as a standalone decla
ration; missing list of enumerators? [-Welaborated-enum-base]
typedef CF_ENUM(CFIndex, CFCharacterSetPredefinedSet) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/jjkm7x4zfifqgsxlbhkamzg0vc9wzip4-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:169:55: note: expanded from macro 'CF_ENUM'
\#define CF_ENUM(...) __CF_ENUM_GET_MACRO(__VA_ARGS__, __CF_NAMED_ENUM, __CF_ANON_ENUM, )(__VA_ARGS__)
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nix/store/jjkm7x4zfifqgsxlbhkamzg0vc9wzip4-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:134:48: note: expanded from macro '__CF_ENUM_GET_MACRO'
\#define __CF_ENUM_GET_MACRO(_1, _2, NAME, ...) NAME
                                               ^
/nix/store/jjkm7x4zfifqgsxlbhkamzg0vc9wzip4-apple-framework-CoreFoundation-11.0.0/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:142:75: note: expanded from macro '__CF_NAMED_ENUM'
\#define __CF_NAMED_ENUM(_type, _name)     enum __CF_ENUM_ATTRIBUTES _name : _type _name; enum _name : _type                                                                                                                                                                                                                                               ^~~~~~~
...
```