lower proto recursion limit (#21629)
* Package changes

* Added test that runs invalid package

* Almost working, but wrong payload import?

daml-lf/archive/src/test/scala/com/digitalasset/daml/lf/archive/DecodeV2Spec.scala:1598: error: type mismatch;
 found   : com.digitalasset.daml.lf.archive.DamlLf.ArchivePayload
 required: com.digitalasset.daml.lf.archive.ArchivePayload

* Compiles, but no dice on the right error

* Test now properly detects proto limit

* Also increase limit in moduleDecoder

* copilot review