Ensure interface generation uses package prefixes (#15215)
* Ensure interface generation uses package prefixes

CHANGELOG_BEGIN
- [BUGFIX] Interface generation now respects package prefixes argument. This means generated interfaces will now be placed in the right subpackages.
CHANGELOG_END

* Prove that we get an error if interface is generated in the wrong directory

Command: bazel build //language-support/java/codegen:test-daml-java.jar

Error:
bazel-out/darwin_arm64-opt/bin/language-support/java/codegen/_javac/test-daml-java.jar/libtest-daml-java.jar_tmp/blah/ut/retro/InterfaceRetro.java:24: error: cannot find symbol
  public static final ChoiceMetadata<ut.retro.InterfaceRetro, Transfer, ut.retro.InterfaceRetro.ContractId> CHOICE_Transfer =
                                             ^
  symbol:   class InterfaceRetro
  location: package ut.retro
bazel-out/darwin_arm64-opt/bin/language-support/java/codegen/_javac/test-daml-java.jar/libtest-daml-java.jar_tmp/blah/ut/retro/InterfaceRetro.java:24: error: package ut.retro.InterfaceRetro does not exist
  public static final ChoiceMetadata<ut.retro.InterfaceRetro, Transfer, ut.retro.InterfaceRetro.ContractId> CHOICE_Transfer =

* Revert "Prove that we get an error if interface is generated in the wrong directory"

This reverts commit cc8612a8a32e3cb73dbfd2e5804733b42f233f18.