bazel migration 7 nobzlmod (#21041)
* Upgrade Bazel 5.2 to 5.4.1

- nixpkgs 23.05
- rules_nixpkgs 0.10
- rules_haskell 0.16
- rules_go 0.40
- go_googleapis 2022-12-05
- protobuf 3.19

* Upgrade Bazel 5.4.1 to 6.5.0.

- rules_haskell -> 1.0
- rules_nodejs -> 5.8.5
- rules_pkg -> 1.0.1
- bazel_gazelle -> 0.42
- lodash -> 4.5 (bounded by mojotech validation library)
- jest -> 27
- typescript -> 5.8
- remove deprecated nodejs-14

* Fix port generation bounds

* Bazel6: Remove unecessary `--strip-components=1` when packaging templates

* Bazel6: Pin nixpkgs to latest commit on the 24.05 branch

Previously it was pinned to the tag which does not include hotfixes.

* Bazel6: Disable REPL testing which cause memory allocation issue

* Bazel6: Fix build on Windows

- Add nodejs-18

* Upgrade Bazel 6.5.0 to 7.1.0.

* SQUASH: Turn back on the java memory option

* Bazel7: Fix MacOS build.

* SQUASH: Update platforms to 0.0.11

* SQUASH: Pin latest `build_bazel_apple_support` version

* SQUASH: Windows fix

* SQUASH: Update cabal dependencies

* SQUASH: Windows fixes

* SQUASH.MacOS: update rules_pkg

* SQUASH.MacOS: Fix error message in `fat_cc_library`.

* SQUASH.MacOS: Attempt to use same logic accross platform

* SQUASH.Windows: Update bazel version in manifest

* SQUASH.Windows: more fixes

* SQUASH: Fix pkg-db files resolution for MacOS

* SQUASH: Fix platforms definition in BUILD

* SQUASH: Fix OS CPU string for MacOS

* SQUASH: Fixing rules_nikpkgs for darwin

* SQUASH: Use scala_major_version for all scala deps

* SQUASH: Fix MacOS cc-toolchain

* SQUASH: MacOS fix mktemp usage from cc toolchain

* SQUASH: Make cpu parametric when building daml-extension

* SQUASH: Fix jvm toolchain for Windows

* SQUASH: Java code fixes for Windows

* SQUASH: Expose `go` in env

* SQUASH: Clean patches

* SQUASH: MacOS fix

* SQUASH: Compatiblity_Linux remove unused patches

* SQUASH: cleaning

* SQUASH: More cleaning and sync-up compatibility

* DEBUG: Attempt to fix cache poisoning

* SQUASH: Fix compatibility build

* build --experimental_remote_cache_eviction_retries=1

* Disable builds without the bytes

* sync .bazelrc

* Remove nodejs_dev_env

rules_nodejs fetches a binary release of the NodeJS toolchain instead.

* DEBUG toolchain resolution

* update git on Windows

```
ERROR: D:/a/2/a/daml/sdk/WORKSPACE:567:18: fetching dadew_binary_bundle
rule //external:dadew_ghc_lib_deps:
 Traceback (most recent call last): File "D:/a/2/a/daml/sdk/bazel_tools/dev_env_tool/dev_env_tool.bzl", line 303, column 13, in _dadew_binary_bundle_impl fail("Missing paths in '{}': {}".format(tool_home, ", ".join(missing))) Error in fail: Missing paths in 'C:\Users\u\dadew\scoop\apps\msys2\current': usr/lib/git-core/git
```

* consistent msys2 version tag

* Use Scoop git instead of msys2

The msys2 git package seems to be missing the actual git binary at the
expected path.

* platform specific Java runtime toolchain

The nixpkgs toolchain is not available on Windows.

* avoid missing _iface for empty packages

* Reference upstream PR

* Add optional libcxxabi to Darwin cc

This resolves a linker segmentation fault on MacOS
```
HaskellLinkBinary release/release failed... (from target //release:release)
...
/nix/store/...-clang-wrapper-16.0.6/bin/ld: line 269: 81270 Segmentation fault: 11
```

* Revert "DEBUG toolchain resolution"

This reverts commit d9261e69455d766af4f5efd5b499a2de80504f93.

* Revert to old node_deps_cache script

Encountered absolute symlink targets in the output of the newer version.

* Some of the files are directories, use `cp -r`

* Dereference symlinks

* Handle shallow node_modules inputs

Directories that lie directly underneath `node_modules` lead to an empty
string value for `$dir`.

* os_info: handle MacOS x86_64 case

* package_app resolve symlinks in cp

* DEBUG

* Copy with cat to avoid symlink resolution issues

* build:macos -> build:darwin

* Revert "DEBUG"

This reverts commit 7cc71aff94e3df0266e6073b59163d97db336600.

* Explicit resource file copy

Avoid recursive directory copies which can capture unwanted inputs on
Windows where build actions are not sandboxed.

* fix compatibility .bazelrc

* Explicit 127.0.0.1 for build-and-lint-test

Tests fail on MacOS with errors of the form
```
● decoders for recursive types do not loop › recursive enum

    FetchError: request to http://localhost:62036/v1/packages failed,
    reason: connect ECONNREFUSED ::1:62036
```

It seems that localhost resolves to ipv6 ::1 instead of the expected
ipv4 127.0.0.1.

* Revert "SQUASH: Update cabal dependencies"

This reverts commit 79f18d9f97cc1a98a985ca5c4511247a539610cb.

* Update Cabal file generation

The logic to detect dependencies needed to be adapted for canonical
labels (`@@` prefix).

* Revert "Bazel6: Disable REPL testing which cause memory allocation issue"

This reverts commit 1c80f09e1f83ed3419bcdf5811df106b15961e0a.

* Fix ambiguous da-ghci entry point

* Disable da-ghci test again

* TMP Enable M1 CI

Cherry-picking https://github.com/digital-asset/daml/pull/20736

* TMP loop build

MacOS M1 builds fail with transient linker segmentation faults. This is
to retry the build many times to see if the build passes in the end.

* Revert "TMP loop build"

This reverts commit a209e470bcab8899afc728e8601ba706d6af276d.

* Revert "TMP Enable M1 CI"

This reverts commit 92ae78baba1ba2e10e5179ef66f5991d8bbd669b.

* comment on if not is_windows

* Remove unused patch files

* Update haskell-opt patch

* Reinstate MavenInfo expectation

* Fix POM file workspace remapping

* Update .hie-bios

Uses the new @bios rules_haskell targets.

* Fix HLS build - add bzip2

* fix bzip2 formatting

* drop whitespace changes from rules_haskell PR

* Drop no-longer valid "darwin" cpu value

* remove unused patches

* Remove unused yarn.lock dep

* remove redundant lambda

* re-enable GOPROXY

* remove dead code

---------

Co-authored-by: Samuel Williams <samuel.williams@digitalasset.com>
Co-authored-by: Andreas Herrmann <andreas.herrmann@tweag.io>