Reformat string since da-ghci does not like the `\`'s (#22249)
`da-ghci` does not like the backslashes in DA.Pretty (we get some weird
lexing error), so I replaced them with a unlines instead (concat would
have been the direct replacement but @samuel-williams-da preferred the
css to have newlines)
```
[23 of 42] Compiling DA.Pretty        ( libs-haskell/da-hs-base/src/DA/Pretty.hs, libs-haskell/da-hs-base/src/DA/Pretty.o ) [flags changed]

libs-haskell/da-hs-base/src/DA/Pretty.hs:331:25: error:
    lexical error in string/character literal at character '.'
    |
331 | highlightStylesheet = "\
    |                         ^
Failed, 22 modules loaded.
```