Almost working, but wrong payload import?
daml-lf/archive/src/test/scala/com/digitalasset/daml/lf/archive/DecodeV2Spec.scala:1598: error: type mismatch;
 found   : com.digitalasset.daml.lf.archive.DamlLf.ArchivePayload
 required: com.digitalasset.daml.lf.archive.ArchivePayload