Fix CI build on windows (#14279) (#14282)
Prior to this change the installation of msys2 would fail because packages fail
to validate their signature:

```
:: File /var/cache/pacman/pkg/perl-HTTP-Cookies-6.10-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP s
ignature)).
Do you want to delete it? [Y/n]
error: perl-Net-SSLeay: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
:: File /var/cache/pacman/pkg/perl-Net-SSLeay-1.90-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP
signature)).
Do you want to delete it? [Y/n]
error: failed to commit transaction (invalid or corrupted package)
```

Also removes references to daml-binaries.da-ext.net.

CHANGELOG_BEGIN
CHANGELOG_END

Co-authored-by: Gary Verhaegen <gary.verhaegen@digitalasset.com>
Co-authored-by: Claudio Bley <103681498+cbley-da@users.noreply.github.com>