TMP Disable non-Linux CI
- MacOS fails due to C compiler error:
    ```
    In file included from src/main/cpp/blaze_util_darwin.cc:24:
    /nix/store/mkfq1a1i6n66fahlcjvw890xj32zvlqp-Libsystem-osx-10.11.6/include/pthread/spawn.h:65:34: error: unknown type name 'qos_class_t'; did you mean 'au_class_t'?
                                     qos_class_t __qos_class);
                                     ^
    /nix/store/mkfq1a1i6n66fahlcjvw890xj32zvlqp-Libsystem-osx-10.11.6/include/bsm/audit.h:176:19: note: 'au_class_t' declared here
    typedef u_int32_t       au_class_t;
    ```
- Windows needs to be updated to Bazel 0.25 separately
- For now we just want to test "builds without the bytes" on Linux