Try ScalaPB update to 0.11.9 / 0.9.9
In an attempt to address the following error
```
java.lang.NoSuchMethodError: 'java.lang.Object com.google.protobuf.DescriptorProtos$FileOptions.getExtension(com.google.protobuf.GeneratedMessage$GeneratedExtension)'
```