Explicit 127.0.0.1 for build-and-lint-test
Tests fail on MacOS with errors of the form
```
● decoders for recursive types do not loop › recursive enum

    FetchError: request to http://localhost:62036/v1/packages failed,
    reason: connect ECONNREFUSED ::1:62036
```

It seems that localhost resolves to ipv6 ::1 instead of the expected
ipv4 127.0.0.1.