sandbox: Do not re-register the metrics when resetting.
This can cause an issue because we cannot register JMX metrics twice. We
end up with fun exceptions.

The error looks like this:

```
14:37:26.230 [sandbox-worker-grpc-event-loop-e20f0542-e2c0-452d-bf7c-0ba58cda6145-31-1] DEBUG com.codahale.metrics.jmx.JmxReporter - Unable to register timer
javax.management.InstanceAlreadyExistsException: com.daml.platform.sandbox.SandboxServer:name=daml.lapi.reset_service.reset,type=timers
```

Seen in a flaky test on CI.

CHANGELOG_BEGIN
CHANGELOG_END