update git on Windows
```
ERROR: D:/a/2/a/daml/sdk/WORKSPACE:567:18: fetching dadew_binary_bundle
rule //external:dadew_ghc_lib_deps:
 Traceback (most recent call last): File "D:/a/2/a/daml/sdk/bazel_tools/dev_env_tool/dev_env_tool.bzl", line 303, column 13, in _dadew_binary_bundle_impl fail("Missing paths in '{}': {}".format(tool_home, ", ".join(missing))) Error in fail: Missing paths in 'C:\Users\u\dadew\scoop\apps\msys2\current': usr/lib/git-core/git
```