Add flag name to -W<error> flag errors (#22893)
From Itai:

Small feature request for damlc:
```
Error:  option -W: Warning flag is not valid - warning flags must be of the form `-Werror=<name>`, `-Wno-<name>`, or `-
W<name>`. Available names are: deprecated-exceptions, crypto-text-is-alpha, upgrade-interfaces, upgrade-exceptions, 
upgrade-dependency-metadata, upgraded-template-expression-changed, upgraded-choice-expression-changed, could-
not-extract-upgraded-expression, unused-dependency, upgrades-own-dependency, template-interface-depends-on-daml-
script, template-has-new-interface-instance
```
Can this please tell me which -W flag it found not to be valid? I was
staring at this for an hour until I realized where the flags were coming
from (they were in daml.yaml). If this had told me what invalid flag it
received, I would have just grepped for that. Thanks