Attempt at fixing a flaky test in Canton (#16497)
Canton fails because this error appears in the logs:
```
SEVERE: Exception while executing runnable io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed@4e6759b5
java.lang.IllegalStateException: Promise already completed.
	at com.daml.grpc.adapter.utils.BufferingObserver.onError(BufferingObserver.scala:19)
```